# -*- coding: utf-8 -*-
"""format.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qg7W9KkEOKAh05suGXf3Tpk6AExubMtB
"""


def format_1_line(text):
    text = text.upper()
    tmp = text
    error = 1
    if len(text.split('-')) != 2:
        rest = ''
    else:
        text = text.split('-')[0]
        rest = tmp.split('-')[1]
    if len(text) != 3 and len(text) != 4:
        return text + '-' + rest
    if len(text) == 4:
        # fix 1st and 2nd position
        if text[0] == 'S':
            text = '5' + text[1:4]
        # g->9
        if text[0] == 'G' and text[1] == 'G':
            text = '99' + text[2] + text[3]
        if text[0] == 'G':
            text = '9' + text[1:4]
        if text[1] == 'G':
            text = text[0] + '9' + text[2:4]
        # O->0
        if text[0] == 'O' and text[1] == 'O':
            text = '00' + text[2] + text[3]
        if text[0] == 'O':
            text = '0' + text[1:4]
        if text[1] == 'O':
            text = text[0] + '0' + text[2:4]
        # T->1
        if text[0] == 'T' and text[1] == 'T':
            text = '11' + text[2] + text[3]
        if text[1] == 'T':
            text = text[0] + '1' + text[2:4]
        # Z->2
        if text[0] == 'Z' and text[1] == 'Z':
            text = '22' + text[2] + text[3]
        if text[0] == 'Z':
            text = '2' + text[1:4]
        if text[1] == 'Z':
            text = text[0] + '2' + text[2:4]
        # B->8
        if text[0] == 'B' and text[1] == 'B':
            text = '88' + text[2] + text[3]
        if text[0] == 'B':
            text = '8' + text[1:4]
        if text[1] == 'B':
            text = text[0] + '8' + text[2:4]
        # fix 3rd position
        if (text[2] == '0' and text[0] != 'T'):
            text = text[:2] + 'D' + text[3]
        if (text[2] == '1'):
            text = text[:2] + 'H' + text[3]
        if (text[2] == '2'):
            text = text[:2] + 'Z' + text[3]
        if (text[2] == '8'):
            text = text[:2] + 'B' + text[3]
        if (text[2] == '9' and text[0] != 'T'):
            text = text[:2] + 'D' + text[3]
        # fix 4th position
        if text[3] == '0' and text[0] != 'T':
            text = text[:3] + 'D'
        if text[3] == 'O' and text[0] != 'T':
            text = text[:3] + 'D' + '-' + rest
        else:
            error = 0
    elif len(text) == 3:
        # fix 1st and 2nd position
        if text[0] == 'S':
            text = '5' + text[1:3]

        # G->9
        if text[0] == 'G' and text[1] == 'G':
            text = '99' + text[2]
        if text[0] == 'G':
            text = '9' + text[1:3]
        if text[1] == 'G':
            text = text[0] + '9' + text[2]
        # O->0
        if text[0] == 'O' and text[1] == 'O':
            text = '00' + text[2]
        if text[0] == 'O':
            text = '0' + text[1:3]
        if text[1] == 'O':
            text = text[0] + '0' + text[2]
        # T->1
        # if text[0] == 'T' and text [1] == 'T':
        #   text = '11'+text[2]
        # if text[0] == 'T':
        #   text = '1'+ text[1:3]
        if text[1] == 'T':
            text = text[0] + '1' + text[2]
        # Z->2
        if text[0] == 'Z' and text[1] == 'Z':
            text = '22' + text[2]
        if text[0] == 'Z':
            text = '2' + text[1:3]
        if text[1] == 'Z':
            text = text[0] + '2' + text[2]
        # B->8
        if text[0] == 'B' and text[1] == 'B':
            text = '88' + text[2]
        if text[0] == 'B':
            text = '8' + text[1:3]
        if text[1] == 'B':
            text = text[0] + '8' + text[2]
        # fix the 3rd position
        if (text[2] == '0' or text[2] == 'O'):
            text = text[:2] + 'D'
        # if(text[2]=='1'):
        #   text = text[:2]+'H'
        if (text[2] == '2'):
            text = text[:2] + 'Z'
        if (text[2] == '8'):
            text = text[:2] + 'B'
        if (text[2] == '9'):
            text = text[:2] + 'D' + '-' + rest
        else:
            error = 0
    if error == 0:
        return text + '-' + rest
    else:
        return format_1_line(text)
  
# result = '510-364.35'
# result = format_1_line(result)
# print(result)